name: Checks

on:
  push:
    branches:
      - flakes
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  fmt-check:
    runs-on:
      - x64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run fmt check
        run: nix build .#checks.x86_64-linux.fmt-check -L --show-trace

  system-build-x64:
    runs-on:
      - x64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build SelfPrivacy system for x86_64
        run: nix build .#checks.x86_64-linux.system-eval -L --show-trace

      - name: Upload cache
        if: >
          github.repository == 'SelfPrivacy/selfprivacy-nixos-config' &&
          (github.event_name != 'pull_request' ||
          github.event.pull_request.head.repo.full_name == github.repository)
        env:
          ATTIC_TOKEN: ${{ secrets.ATTIC_TOKEN }}
        run: |
          attic login --set-default selfprivacy https://cache.selfprivacy.org "$ATTIC_TOKEN"
          nix build .#checks.x86_64-linux.system-eval --no-link --print-out-paths | xargs attic push selfprivacy:nixos

  system-first-boot-x64:
    needs:
      - system-build-x64

    runs-on:
      - kvm

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run SelfPrivacy first boot tests with admin user
        run: nix build .#checks.x86_64-linux.first-boot-legacy-unix-user -L --show-trace

      - name: Run SelfPrivacy first boot tests without admin user
        run: nix build .#checks.x86_64-linux.first-boot-no-legacy-unix-user -L --show-trace

      - name: Run SelfPrivacy first boot tests with all modules enabled
        run: nix build .#checks.x86_64-linux.first-boot-with-all-modules -L --show-trace

  # We don't have arm64 linux runners yet, so let's just check that evaluation is fine for now.
  system-eval-arm64:
    runs-on:
      - x64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Eval SelfPrivacy system for aarch64
        run: nix eval .#checks.aarch64-linux.system-eval -L --show-trace
