name: Checks

on:
  push:
    branches:
      - flakes
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  flake-check:
    runs-on:
      - x64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run flake checks
        run: nix flake check -L --show-trace

      - name: Upload cache
        if: github.repository == 'SelfPrivacy/selfprivacy-nixos-config'
        env:
          ATTIC_TOKEN: ${{ secrets.ATTIC_TOKEN }}
        run: |
          attic login --set-default selfprivacy https://cache.selfprivacy.org "$ATTIC_TOKEN"
          nix build .#checks.x86_64-linux.system-eval --no-link --print-out-paths | xargs attic push selfprivacy:nixos
